training_queries: data/OHSUMED/Fold1/train.txt
test_queries: data/OHSUMED/Fold1/test.txt
feature_count: 45
seed: 42
num_runs: 1
num_queries: 10
query_sampling_method: random
output_dir: outdir
output_prefix: Fold1
user_model: user.CascadeUserModel
output_dir_overwrite: False
user_model_args:
    --p_click 0:0.0,1:0.5,2:1.0
    --p_stop 0:0.0,1:0.0,2:0.0
system: system.GALearningSystem
system_args:
    --init_weights random
    --sample_weights sample_unit_sphere
    --comparison interleave.GATeamDraftMultileave
    --comparison_args random
    --delta 0.1
    --alpha 0.01
    --ranker ranker.GARankingFunction
    --ranker_arg 3
    --ranker_tie random
    --seed 42
    --num_rankers 10
    --update wm
evaluation:
    - evaluation.NdcgEval cutoff 1
    - evaluation.NdcgEval cutoff 3
    - evaluation.NdcgEval cutoff 5
    - evaluation.NdcgEval cutoff 7
    - evaluation.NdcgEval cutoff 10