num_runs: 10
num_queries: 23
query_sampling_method: random
user_model: environment.CascadeUserModel
system: retrieval_system.ListwiseLearningSystem
seed: 42
system_args:
    --init_weights random
    --sample_weights sample_unit_sphere
    --comparison comparison.DocumentConstraints
    --comparison_args random
    --delta 0.1
    --alpha 0.01
    --ranker ranker.ProbabilisticRankingFunction
    --ranker_arg 3
    --ranker_tie random
    --processes 4
experimenter: experiment.LearningExperiment
output_dir: outdir
output_dir_overwrite: True
evaluation:
    - evaluation.NdcgEval cutoff 1
    - evaluation.NdcgEval cutoff 3
    - evaluation.NdcgEval cutoff 5
    - evaluation.NdcgEval cutoff 7
    - evaluation.NdcgEval cutoff 10
meta: --data OHSUMED,64,3
   --data_dir data
   --output_base outdir-pi
   --experiment_name test_meta
   --platform local
   --um per nav inf
   --uma per,5,0:0.0,1:0.0,2:0.0,3:0.0,4:1.0,0:0.0,1:0.0,2:0.0,3:0.0,4:1.0
         nav,5,0:0.05,1:0.2,2:0.4,3:0.5,4:0.95,0:0.1,1:0.3,2:0.4,3:0.5,4:0.9
         inf,5,0:0.4,1:0.5,2:0.6,3:0.7,4:0.9,0:0.1,1:0.2,2:0.3,3:0.4,4:0.5
         per,3,0:0.0,1:0.0,2:1.0,0:0.0,1:0.0,2:0.0
         nav,3,0:0.0,1:0.0,2:1.0,0:0.0,1:0.0,2:0.0
         inf,3,0:0.0,1:0.0,2:1.0,0:0.0,1:0.0,2:0.0
   --analysis analysis.SummarizeAnalysis