training_queries: data/OHSUMED/Fold1/train.txt
test_queries: data/OHSUMED/Fold1/test.txt
feature_count: 45
num_runs: 1
num_queries: 10000
query_sampling_method: random
output_dir: outdir
output_prefix: Fold1
user_model: user.CascadeUserModel.CascadeUserModel
user_model_args:
    --p_click 0:0.0,1:0.5,2:1.0
    --p_stop 0:0.0,1:0.0,2:0.0
system: system.WTALearningSystem.WTALearningSystem
system_args:
    --init_weights random
    --num_rankers 10
    --sample_weights sample_unit_sphere
    --comparison interleave.TeamDraftMultileave.TeamDraftMultileave
    --delta 0.1
    --alpha 0.01
    --ranker ranker.ProbabilisticRankingFunction.ProbabilisticRankingFunction
    --ranker_arg 3
    --ranker_tie random
    --update wta
    --seed 42
evaluation:
    - evaluation.NdcgEval.NdcgEval cutoff 1
    - evaluation.NdcgEval.NdcgEval cutoff 3
    - evaluation.NdcgEval.NdcgEval cutoff 5
    - evaluation.NdcgEval.NdcgEval cutoff 7
    - evaluation.NdcgEval.NdcgEval cutoff 10